version: '3.8'
services:
  db:
    image: 'postgres:latest'
    restart: always
    env_file:
      - .env 
    environment:
      - POSTGRES_USER=${db_username}
      - POSTGRES_PASSWORD=${db_password}
      - POSTGRES_DB=${db_name}
    ports:
      - '5432:5432'
    volumes:
      - cll:/var/lib/postgresql/data
  api:
    build: ./continual_learning/backend
    restart: always
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - db
  frontend:
    build: ./continual_learning/frontend
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - api
volumes:
  cll:
