import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ChatProvider } from '@/app/ChatContext';
import Sidebar from '@/app/components/Sidebar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ChatProvider>
    <html lang="en">
      <body className={inter.className}>
        <main className='flex justify-between align-top h-screen'>
          <div className='columns-1 relative'>
            <Sidebar />
          </div>
          <div className="columns-1 w-full relative bg-contentmain">
          {children}
          </div>
        </main>
      </body>
    </html>
    </ChatProvider>
  )
}
